/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'pin' : string,
  'houseNumber' : string,
  'city' : string,
  'state' : string,
}
export interface AltPaymentRecord {
  'status' : string,
  'paymentMethod' : string,
  'orderId' : OrderId,
  'timestamp' : Timestamp,
  'amount' : number,
  'transactionId' : string,
}
export type ContactId = bigint;
export interface ContactSubmission {
  'id' : ContactId,
  'name' : string,
  'submittedAt' : Timestamp,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export interface CreateCheckoutSessionRequest {
  'lineItems' : Array<StripeLineItem>,
  'cancelUrl' : string,
  'orderId' : OrderId,
  'successUrl' : string,
}
export type CreateCheckoutSessionResult = { 'ok' : string } |
  { 'err' : string };
export interface DashboardStats {
  'totalProducts' : bigint,
  'cancelledOrders' : bigint,
  'totalOrders' : bigint,
  'damagedOrders' : bigint,
  'refundedOrders' : bigint,
  'uniqueCustomers' : bigint,
  'inStockCount' : bigint,
  'deliveredOrders' : bigint,
}
export interface InventoryItem {
  'inStock' : boolean,
  'productId' : ProductId,
  'updatedAt' : Timestamp,
}
export interface LoginEvent {
  'method' : LoginMethod,
  'principal' : UserId,
  'displayName' : [] | [string],
  'timestamp' : Timestamp,
}
export type LoginMethod = { 'admin' : null } |
  { 'internetIdentity' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'isDamaged' : boolean,
  'total' : number,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'address' : Address,
  'items' : Array<OrderItem>,
  'stripeTransactionId' : [] | [string],
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'refunded' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null } |
  { 'cashfree' : null } |
  { 'razorpay' : null } |
  { 'paypal' : null } |
  { 'online' : null };
export type PaymentStatus = { 'err' : string } |
  { 'expired' : null } |
  { 'paid' : null } |
  { 'unpaid' : null };
export interface PlaceOrderRequest {
  'paymentMethod' : PaymentMethod,
  'address' : Address,
  'items' : Array<OrderItem>,
  'stripeTransactionId' : [] | [string],
}
export type ProductId = string;
export interface ProductUpdate {
  'inStock' : [] | [boolean],
  'price' : [] | [number],
}
export interface Review {
  'id' : ReviewId,
  'text' : string,
  'productId' : ProductId,
  'reviewerName' : string,
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface StripeLineItem {
  'name' : string,
  'priceRupees' : number,
  'quantity' : bigint,
}
export type Timestamp = bigint;
export interface UpiPaymentRecord {
  'status' : string,
  'upiTransactionId' : string,
  'orderId' : OrderId,
  'timestamp' : Timestamp,
  'amount' : bigint,
}
export type UserId = Principal;
export interface _SERVICE {
  'adminDeleteProduct' : ActorMethod<
    [string, ProductId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminFlagOrderDamaged' : ActorMethod<
    [string, OrderId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllOrders' : ActorMethod<[string], Array<Order>>,
  'adminGetAllReviews' : ActorMethod<[string], Array<Review>>,
  'adminGetAltPayments' : ActorMethod<[string], Array<AltPaymentRecord>>,
  'adminGetContactSubmissions' : ActorMethod<
    [string],
    Array<ContactSubmission>
  >,
  'adminGetDamagedOrders' : ActorMethod<[string], Array<Order>>,
  'adminGetDashboardStats' : ActorMethod<[string], [] | [DashboardStats]>,
  'adminGetInventory' : ActorMethod<[string], Array<InventoryItem>>,
  'adminGetLoginHistory' : ActorMethod<[string], Array<LoginEvent>>,
  'adminGetOutOfStockProducts' : ActorMethod<[string], Array<InventoryItem>>,
  'adminGetUpiPayments' : ActorMethod<[string], Array<UpiPaymentRecord>>,
  'adminMarkContactRead' : ActorMethod<
    [string, ContactId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateOrderPaymentStatus' : ActorMethod<
    [string, OrderId, string],
    boolean
  >,
  'adminUpdateOrderStatus' : ActorMethod<
    [string, OrderId, OrderStatus],
    boolean
  >,
  'adminUpdateProduct' : ActorMethod<
    [string, ProductId, ProductUpdate],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateStock' : ActorMethod<
    [string, ProductId, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminVerifyPassword' : ActorMethod<[string], boolean>,
  'cancelOrder' : ActorMethod<[OrderId], boolean>,
  'createStripeCheckoutSession' : ActorMethod<
    [CreateCheckoutSessionRequest],
    CreateCheckoutSessionResult
  >,
  'getAverageRating' : ActorMethod<[string], [] | [number]>,
  'getReviews' : ActorMethod<[string], Array<Review>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], Order>,
  'recordAltPayment' : ActorMethod<
    [OrderId, string, string, number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recordLogin' : ActorMethod<[LoginMethod, [] | [string]], undefined>,
  'recordUpiPayment' : ActorMethod<
    [OrderId, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string],
    { 'ok' : ContactId } |
      { 'err' : string }
  >,
  'submitReview' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : ReviewId } |
      { 'err' : string }
  >,
  'verifyStripePayment' : ActorMethod<[string], PaymentStatus>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];