/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Null,
  'cashfree' : IDL.Null,
  'razorpay' : IDL.Null,
  'paypal' : IDL.Null,
  'online' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Address = IDL.Record({
  'pin' : IDL.Text,
  'houseNumber' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'isDamaged' : IDL.Bool,
  'total' : IDL.Float64,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'address' : Address,
  'items' : IDL.Vec(OrderItem),
  'stripeTransactionId' : IDL.Opt(IDL.Text),
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'text' : IDL.Text,
  'productId' : ProductId,
  'reviewerName' : IDL.Text,
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});
export const AltPaymentRecord = IDL.Record({
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'orderId' : OrderId,
  'timestamp' : Timestamp,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'cancelledOrders' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'damagedOrders' : IDL.Nat,
  'totalRazorpayTransactions' : IDL.Nat,
  'totalRazorpayRevenue' : IDL.Nat,
  'refundedOrders' : IDL.Nat,
  'uniqueCustomers' : IDL.Nat,
  'inStockCount' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'inStock' : IDL.Bool,
  'productId' : ProductId,
  'updatedAt' : Timestamp,
});
export const LoginMethod = IDL.Variant({
  'admin' : IDL.Null,
  'internetIdentity' : IDL.Null,
});
export const LoginEvent = IDL.Record({
  'method' : LoginMethod,
  'principal' : UserId,
  'displayName' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
});
export const RazorpayPaymentRecord = IDL.Record({
  'razorpayPaymentId' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'errorMessage' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : OrderId,
  'razorpayOrderId' : IDL.Text,
  'userPrincipal' : IDL.Text,
  'timestamp' : Timestamp,
  'items' : IDL.Vec(OrderItem),
  'amount' : IDL.Nat,
});
export const RazorpayStats = IDL.Record({
  'failedCount' : IDL.Nat,
  'successCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalTransactions' : IDL.Nat,
});
export const UpiPaymentRecord = IDL.Record({
  'status' : IDL.Text,
  'upiTransactionId' : IDL.Text,
  'orderId' : OrderId,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
});
export const ProductUpdate = IDL.Record({
  'inStock' : IDL.Opt(IDL.Bool),
  'price' : IDL.Opt(IDL.Float64),
});
export const StripeLineItem = IDL.Record({
  'name' : IDL.Text,
  'priceRupees' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const CreateCheckoutSessionRequest = IDL.Record({
  'lineItems' : IDL.Vec(StripeLineItem),
  'cancelUrl' : IDL.Text,
  'orderId' : OrderId,
  'successUrl' : IDL.Text,
});
export const CreateCheckoutSessionResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const PlaceOrderRequest = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'address' : Address,
  'items' : IDL.Vec(OrderItem),
  'stripeTransactionId' : IDL.Opt(IDL.Text),
});
export const PaymentStatus = IDL.Variant({
  'err' : IDL.Text,
  'expired' : IDL.Null,
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});

export const idlService = IDL.Service({
  'adminDeleteProduct' : IDL.Func(
      [IDL.Text, ProductId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminFlagOrderDamaged' : IDL.Func(
      [IDL.Text, OrderId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'adminGetAllReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], []),
  'adminGetAltPayments' : IDL.Func([IDL.Text], [IDL.Vec(AltPaymentRecord)], []),
  'adminGetContactSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      [],
    ),
  'adminGetDamagedOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'adminGetDashboardStats' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DashboardStats)],
      [],
    ),
  'adminGetInventory' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], []),
  'adminGetLoginHistory' : IDL.Func([IDL.Text], [IDL.Vec(LoginEvent)], []),
  'adminGetOutOfStockProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventoryItem)],
      [],
    ),
  'adminGetRazorpayPayments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RazorpayPaymentRecord)],
      [],
    ),
  'adminGetRazorpayStats' : IDL.Func([IDL.Text], [IDL.Opt(RazorpayStats)], []),
  'adminGetUpiPayments' : IDL.Func([IDL.Text], [IDL.Vec(UpiPaymentRecord)], []),
  'adminMarkContactRead' : IDL.Func(
      [IDL.Text, ContactId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateOrderPaymentStatus' : IDL.Func(
      [IDL.Text, OrderId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminUpdateOrderStatus' : IDL.Func(
      [IDL.Text, OrderId, OrderStatus],
      [IDL.Bool],
      [],
    ),
  'adminUpdateProduct' : IDL.Func(
      [IDL.Text, ProductId, ProductUpdate],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateStock' : IDL.Func(
      [IDL.Text, ProductId, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminVerifyPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'createStripeCheckoutSession' : IDL.Func(
      [CreateCheckoutSessionRequest],
      [CreateCheckoutSessionResult],
      [],
    ),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
  'getMyRazorpayPayments' : IDL.Func([], [IDL.Vec(RazorpayPaymentRecord)], []),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
  'recordAltPayment' : IDL.Func(
      [OrderId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recordLogin' : IDL.Func([LoginMethod, IDL.Opt(IDL.Text)], [], []),
  'recordRazorpayPayment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        OrderId,
        IDL.Vec(OrderItem),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : RazorpayPaymentRecord, 'err' : IDL.Text })],
      [],
    ),
  'recordUpiPayment' : IDL.Func(
      [OrderId, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ContactId, 'err' : IDL.Text })],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : ReviewId, 'err' : IDL.Text })],
      [],
    ),
  'verifyStripePayment' : IDL.Func([IDL.Text], [PaymentStatus], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'upi' : IDL.Null,
    'cashfree' : IDL.Null,
    'razorpay' : IDL.Null,
    'paypal' : IDL.Null,
    'online' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Address = IDL.Record({
    'pin' : IDL.Text,
    'houseNumber' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'isDamaged' : IDL.Bool,
    'total' : IDL.Float64,
    'paymentMethod' : PaymentMethod,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'address' : Address,
    'items' : IDL.Vec(OrderItem),
    'stripeTransactionId' : IDL.Opt(IDL.Text),
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'text' : IDL.Text,
    'productId' : ProductId,
    'reviewerName' : IDL.Text,
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  const AltPaymentRecord = IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'orderId' : OrderId,
    'timestamp' : Timestamp,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Text,
  });
  const ContactId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'cancelledOrders' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'damagedOrders' : IDL.Nat,
    'totalRazorpayTransactions' : IDL.Nat,
    'totalRazorpayRevenue' : IDL.Nat,
    'refundedOrders' : IDL.Nat,
    'uniqueCustomers' : IDL.Nat,
    'inStockCount' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'inStock' : IDL.Bool,
    'productId' : ProductId,
    'updatedAt' : Timestamp,
  });
  const LoginMethod = IDL.Variant({
    'admin' : IDL.Null,
    'internetIdentity' : IDL.Null,
  });
  const LoginEvent = IDL.Record({
    'method' : LoginMethod,
    'principal' : UserId,
    'displayName' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
  });
  const RazorpayPaymentRecord = IDL.Record({
    'razorpayPaymentId' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'errorMessage' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : OrderId,
    'razorpayOrderId' : IDL.Text,
    'userPrincipal' : IDL.Text,
    'timestamp' : Timestamp,
    'items' : IDL.Vec(OrderItem),
    'amount' : IDL.Nat,
  });
  const RazorpayStats = IDL.Record({
    'failedCount' : IDL.Nat,
    'successCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalTransactions' : IDL.Nat,
  });
  const UpiPaymentRecord = IDL.Record({
    'status' : IDL.Text,
    'upiTransactionId' : IDL.Text,
    'orderId' : OrderId,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
  });
  const ProductUpdate = IDL.Record({
    'inStock' : IDL.Opt(IDL.Bool),
    'price' : IDL.Opt(IDL.Float64),
  });
  const StripeLineItem = IDL.Record({
    'name' : IDL.Text,
    'priceRupees' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const CreateCheckoutSessionRequest = IDL.Record({
    'lineItems' : IDL.Vec(StripeLineItem),
    'cancelUrl' : IDL.Text,
    'orderId' : OrderId,
    'successUrl' : IDL.Text,
  });
  const CreateCheckoutSessionResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const PlaceOrderRequest = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'address' : Address,
    'items' : IDL.Vec(OrderItem),
    'stripeTransactionId' : IDL.Opt(IDL.Text),
  });
  const PaymentStatus = IDL.Variant({
    'err' : IDL.Text,
    'expired' : IDL.Null,
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
  });
  
  return IDL.Service({
    'adminDeleteProduct' : IDL.Func(
        [IDL.Text, ProductId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminFlagOrderDamaged' : IDL.Func(
        [IDL.Text, OrderId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'adminGetAllReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], []),
    'adminGetAltPayments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AltPaymentRecord)],
        [],
      ),
    'adminGetContactSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        [],
      ),
    'adminGetDamagedOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'adminGetDashboardStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DashboardStats)],
        [],
      ),
    'adminGetInventory' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], []),
    'adminGetLoginHistory' : IDL.Func([IDL.Text], [IDL.Vec(LoginEvent)], []),
    'adminGetOutOfStockProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventoryItem)],
        [],
      ),
    'adminGetRazorpayPayments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RazorpayPaymentRecord)],
        [],
      ),
    'adminGetRazorpayStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RazorpayStats)],
        [],
      ),
    'adminGetUpiPayments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UpiPaymentRecord)],
        [],
      ),
    'adminMarkContactRead' : IDL.Func(
        [IDL.Text, ContactId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateOrderPaymentStatus' : IDL.Func(
        [IDL.Text, OrderId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminUpdateOrderStatus' : IDL.Func(
        [IDL.Text, OrderId, OrderStatus],
        [IDL.Bool],
        [],
      ),
    'adminUpdateProduct' : IDL.Func(
        [IDL.Text, ProductId, ProductUpdate],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateStock' : IDL.Func(
        [IDL.Text, ProductId, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminVerifyPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'createStripeCheckoutSession' : IDL.Func(
        [CreateCheckoutSessionRequest],
        [CreateCheckoutSessionResult],
        [],
      ),
    'getAverageRating' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getMyRazorpayPayments' : IDL.Func(
        [],
        [IDL.Vec(RazorpayPaymentRecord)],
        [],
      ),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [Order], []),
    'recordAltPayment' : IDL.Func(
        [OrderId, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recordLogin' : IDL.Func([LoginMethod, IDL.Opt(IDL.Text)], [], []),
    'recordRazorpayPayment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          OrderId,
          IDL.Vec(OrderItem),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : RazorpayPaymentRecord, 'err' : IDL.Text })],
        [],
      ),
    'recordUpiPayment' : IDL.Func(
        [OrderId, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ContactId, 'err' : IDL.Text })],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : ReviewId, 'err' : IDL.Text })],
        [],
      ),
    'verifyStripePayment' : IDL.Func([IDL.Text], [PaymentStatus], []),
  });
};

export const init = ({ IDL }) => { return []; };