/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaceOrderRequest {
    paymentMethod: PaymentMethod;
    address: Address;
    items: Array<OrderItem>;
    stripeTransactionId?: string;
}
export type ContactId = bigint;
export type Timestamp = bigint;
export interface StripeLineItem {
    name: string;
    priceRupees: number;
    quantity: bigint;
}
export interface Address {
    pin: string;
    houseNumber: string;
    city: string;
    state: string;
}
export interface ProductUpdate {
    inStock?: boolean;
    price?: number;
}
export interface OrderItem {
    name: string;
    productId: ProductId;
    quantity: bigint;
    price: number;
}
export interface LoginEvent {
    method: LoginMethod;
    principal: UserId;
    displayName?: string;
    timestamp: Timestamp;
}
export interface CreateCheckoutSessionRequest {
    lineItems: Array<StripeLineItem>;
    cancelUrl: string;
    orderId: OrderId;
    successUrl: string;
}
export interface ContactSubmission {
    id: ContactId;
    name: string;
    submittedAt: Timestamp;
    isRead: boolean;
    email: string;
    message: string;
}
export interface UpiPaymentRecord {
    status: string;
    upiTransactionId: string;
    orderId: OrderId;
    timestamp: Timestamp;
    amount: bigint;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    isDamaged: boolean;
    total: number;
    paymentMethod: PaymentMethod;
    userId: UserId;
    createdAt: Timestamp;
    address: Address;
    items: Array<OrderItem>;
    stripeTransactionId?: string;
}
export interface DashboardStats {
    totalProducts: bigint;
    cancelledOrders: bigint;
    totalOrders: bigint;
    damagedOrders: bigint;
    refundedOrders: bigint;
    uniqueCustomers: bigint;
    inStockCount: bigint;
    deliveredOrders: bigint;
}
export interface InventoryItem {
    inStock: boolean;
    productId: ProductId;
    updatedAt: Timestamp;
}
export type UserId = Principal;
export type CreateCheckoutSessionResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface AltPaymentRecord {
    status: string;
    paymentMethod: string;
    orderId: OrderId;
    timestamp: Timestamp;
    amount: number;
    transactionId: string;
}
export type ReviewId = bigint;
export type ProductId = string;
export type PaymentStatus = {
    __kind__: "err";
    err: string;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "paid";
    paid: null;
} | {
    __kind__: "unpaid";
    unpaid: null;
};
export interface Review {
    id: ReviewId;
    text: string;
    productId: ProductId;
    reviewerName: string;
    timestamp: Timestamp;
    rating: bigint;
}
export type OrderId = bigint;
export enum LoginMethod {
    admin = "admin",
    internetIdentity = "internetIdentity"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    refunded = "refunded",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    cod = "cod",
    upi = "upi",
    cashfree = "cashfree",
    razorpay = "razorpay",
    paypal = "paypal",
    online = "online"
}
export interface backendInterface {
    adminDeleteProduct(password: string, productId: ProductId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminFlagOrderDamaged(password: string, orderId: OrderId, damaged: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllOrders(password: string): Promise<Array<Order>>;
    adminGetAllReviews(password: string): Promise<Array<Review>>;
    adminGetAltPayments(password: string): Promise<Array<AltPaymentRecord>>;
    adminGetContactSubmissions(password: string): Promise<Array<ContactSubmission>>;
    adminGetDamagedOrders(password: string): Promise<Array<Order>>;
    adminGetDashboardStats(password: string): Promise<DashboardStats | null>;
    adminGetInventory(password: string): Promise<Array<InventoryItem>>;
    adminGetLoginHistory(password: string): Promise<Array<LoginEvent>>;
    adminGetOutOfStockProducts(password: string): Promise<Array<InventoryItem>>;
    adminGetUpiPayments(password: string): Promise<Array<UpiPaymentRecord>>;
    adminMarkContactRead(password: string, id: ContactId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateOrderPaymentStatus(password: string, orderId: OrderId, sessionId: string): Promise<boolean>;
    adminUpdateOrderStatus(password: string, orderId: OrderId, newStatus: OrderStatus): Promise<boolean>;
    adminUpdateProduct(password: string, productId: ProductId, updates: ProductUpdate): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateStock(password: string, productId: ProductId, inStock: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminVerifyPassword(password: string): Promise<boolean>;
    cancelOrder(orderId: OrderId): Promise<boolean>;
    createStripeCheckoutSession(request: CreateCheckoutSessionRequest): Promise<CreateCheckoutSessionResult>;
    getAverageRating(productId: string): Promise<number | null>;
    getReviews(productId: string): Promise<Array<Review>>;
    getUserOrders(): Promise<Array<Order>>;
    placeOrder(request: PlaceOrderRequest): Promise<Order>;
    recordAltPayment(orderId: OrderId, paymentMethod: string, transactionId: string, amount: number, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordLogin(method: LoginMethod, displayName: string | null): Promise<void>;
    recordUpiPayment(orderId: OrderId, upiTransactionId: string, amount: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitContactForm(name: string, email: string, message: string): Promise<{
        __kind__: "ok";
        ok: ContactId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitReview(productId: string, reviewerName: string, rating: bigint, text: string): Promise<{
        __kind__: "ok";
        ok: ReviewId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyStripePayment(sessionId: string): Promise<PaymentStatus>;
}
import type { Address as _Address, ContactId as _ContactId, CreateCheckoutSessionResult as _CreateCheckoutSessionResult, DashboardStats as _DashboardStats, LoginEvent as _LoginEvent, LoginMethod as _LoginMethod, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, PlaceOrderRequest as _PlaceOrderRequest, ProductUpdate as _ProductUpdate, ReviewId as _ReviewId, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminDeleteProduct(arg0: string, arg1: ProductId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminFlagOrderDamaged(arg0: string, arg1: OrderId, arg2: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminFlagOrderDamaged(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminFlagOrderDamaged(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllOrders(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllOrders(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllOrders(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllReviews(arg0);
            return result;
        }
    }
    async adminGetAltPayments(arg0: string): Promise<Array<AltPaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAltPayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAltPayments(arg0);
            return result;
        }
    }
    async adminGetContactSubmissions(arg0: string): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetContactSubmissions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetContactSubmissions(arg0);
            return result;
        }
    }
    async adminGetDamagedOrders(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDamagedOrders(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDamagedOrders(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetDashboardStats(arg0: string): Promise<DashboardStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardStats(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardStats(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetInventory(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetInventory(arg0);
            return result;
        }
    }
    async adminGetLoginHistory(arg0: string): Promise<Array<LoginEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetLoginHistory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetLoginHistory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetOutOfStockProducts(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetOutOfStockProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetOutOfStockProducts(arg0);
            return result;
        }
    }
    async adminGetUpiPayments(arg0: string): Promise<Array<UpiPaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUpiPayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUpiPayments(arg0);
            return result;
        }
    }
    async adminMarkContactRead(arg0: string, arg1: ContactId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMarkContactRead(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMarkContactRead(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOrderPaymentStatus(arg0: string, arg1: OrderId, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderPaymentStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderPaymentStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUpdateOrderStatus(arg0: string, arg1: OrderId, arg2: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(arg0, arg1, to_candid_OrderStatus_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(arg0, arg1, to_candid_OrderStatus_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminUpdateProduct(arg0: string, arg1: ProductId, arg2: ProductUpdate): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, arg1, to_candid_ProductUpdate_n18(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, arg1, to_candid_ProductUpdate_n18(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateStock(arg0: string, arg1: ProductId, arg2: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateStock(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateStock(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminVerifyPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminVerifyPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminVerifyPassword(arg0);
            return result;
        }
    }
    async cancelOrder(arg0: OrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async createStripeCheckoutSession(arg0: CreateCheckoutSessionRequest): Promise<CreateCheckoutSessionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createStripeCheckoutSession(arg0);
                return from_candid_CreateCheckoutSessionResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStripeCheckoutSession(arg0);
            return from_candid_CreateCheckoutSessionResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageRating(arg0: string): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRating(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRating(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordAltPayment(arg0: OrderId, arg1: string, arg2: string, arg3: number, arg4: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAltPayment(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAltPayment(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordLogin(arg0: LoginMethod, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLogin(to_candid_LoginMethod_n27(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLogin(to_candid_LoginMethod_n27(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordUpiPayment(arg0: OrderId, arg1: string, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordUpiPayment(arg0, arg1, arg2);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordUpiPayment(arg0, arg1, arg2);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: ContactId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReview(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<{
        __kind__: "ok";
        ok: ReviewId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyStripePayment(arg0: string): Promise<PaymentStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyStripePayment(arg0);
                return from_candid_PaymentStatus_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyStripePayment(arg0);
            return from_candid_PaymentStatus_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CreateCheckoutSessionResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateCheckoutSessionResult): CreateCheckoutSessionResult {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_LoginEvent_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginEvent): LoginEvent {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_LoginMethod_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginMethod): LoginMethod {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DashboardStats]): DashboardStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: _LoginMethod;
    principal: _UserId;
    displayName: [] | [string];
    timestamp: _Timestamp;
}): {
    method: LoginMethod;
    principal: UserId;
    displayName?: string;
    timestamp: Timestamp;
} {
    return {
        method: from_candid_LoginMethod_n14(_uploadFile, _downloadFile, value.method),
        principal: value.principal,
        displayName: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.displayName)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    isDamaged: boolean;
    total: number;
    paymentMethod: _PaymentMethod;
    userId: _UserId;
    createdAt: _Timestamp;
    address: _Address;
    items: Array<_OrderItem>;
    stripeTransactionId: [] | [string];
}): {
    id: OrderId;
    status: OrderStatus;
    isDamaged: boolean;
    total: number;
    paymentMethod: PaymentMethod;
    userId: UserId;
    createdAt: Timestamp;
    address: Address;
    items: Array<OrderItem>;
    stripeTransactionId?: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n5(_uploadFile, _downloadFile, value.status),
        isDamaged: value.isDamaged,
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n7(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        createdAt: value.createdAt,
        address: value.address,
        items: value.items,
        stripeTransactionId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.stripeTransactionId))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    internetIdentity: null;
}): LoginMethod {
    return "admin" in value ? LoginMethod.admin : "internetIdentity" in value ? LoginMethod.internetIdentity : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ContactId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ContactId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ReviewId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ReviewId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    err: string;
} | {
    expired: null;
} | {
    paid: null;
} | {
    unpaid: null;
}): {
    __kind__: "err";
    err: string;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "paid";
    paid: null;
} | {
    __kind__: "unpaid";
    unpaid: null;
} {
    return "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "paid" in value ? {
        __kind__: "paid",
        paid: value.paid
    } : "unpaid" in value ? {
        __kind__: "unpaid",
        unpaid: value.unpaid
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "refunded" in value ? OrderStatus.refunded : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    upi: null;
} | {
    cashfree: null;
} | {
    razorpay: null;
} | {
    paypal: null;
} | {
    online: null;
}): PaymentMethod {
    return "cod" in value ? PaymentMethod.cod : "upi" in value ? PaymentMethod.upi : "cashfree" in value ? PaymentMethod.cashfree : "razorpay" in value ? PaymentMethod.razorpay : "paypal" in value ? PaymentMethod.paypal : "online" in value ? PaymentMethod.online : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoginEvent>): Array<LoginEvent> {
    return value.map((x)=>from_candid_LoginEvent_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n3(_uploadFile, _downloadFile, x));
}
function to_candid_LoginMethod_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoginMethod): _LoginMethod {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderRequest_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderRequest): _PlaceOrderRequest {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUpdate_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdate): _ProductUpdate {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock?: boolean;
    price?: number;
}): {
    inStock: [] | [boolean];
    price: [] | [number];
} {
    return {
        inStock: value.inStock ? candid_some(value.inStock) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    address: Address;
    items: Array<OrderItem>;
    stripeTransactionId?: string;
}): {
    paymentMethod: _PaymentMethod;
    address: _Address;
    items: Array<_OrderItem>;
    stripeTransactionId: [] | [string];
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n25(_uploadFile, _downloadFile, value.paymentMethod),
        address: value.address,
        items: value.items,
        stripeTransactionId: value.stripeTransactionId ? candid_some(value.stripeTransactionId) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.refunded ? {
        refunded: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cod: null;
} | {
    upi: null;
} | {
    cashfree: null;
} | {
    razorpay: null;
} | {
    paypal: null;
} | {
    online: null;
} {
    return value == PaymentMethod.cod ? {
        cod: null
    } : value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cashfree ? {
        cashfree: null
    } : value == PaymentMethod.razorpay ? {
        razorpay: null
    } : value == PaymentMethod.paypal ? {
        paypal: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoginMethod): {
    admin: null;
} | {
    internetIdentity: null;
} {
    return value == LoginMethod.admin ? {
        admin: null
    } : value == LoginMethod.internetIdentity ? {
        internetIdentity: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
